### ISSUE TITLE
Bytes for individual channels

### ISSUE THREAD

**Issue by shurru** [thearn/pyemotiv#1]
Hi, 

Where did you get the documentation for the bytes corresponding to the individual channels? 

SS

**Comment by thearn** [comment]
If I remember right, I was able to get the C commands used to communicate with the Epoc by looking at the Emotiv SDK examples, then wrapping the SDK's dll files using python's ctypes library directly. I think the channels are specified in the SDK as integers valued 0 through 13 (would have to check that again though).

I hope that's helpful.

**Comment by shurru** [comment]
Hey, I figured out the channels I needed :) Thanks so much.
